### ISSUE TITLE
D1.4.6.3 Profile overrides in the target instance summary

### ISSUE THREAD

**Issue by hannakoppelaar** [DIA-NZ/webcurator#52] opened 2018-08-14 14:34 UTC
The target instance summary page contains the option to override the profile at the instance level. This functionality does not yet support imported profiles. We will add an XML editor as in the case of D1.4.6.2.

**Comment by kurtlenfesty** [comment] 2018-09-28 03:53
Working on this issue in branch: [feature/D1.4.6.3_profile_overrides_in_target_instance_summary] (https://github.com/DIA-NZ/webcurator/tree/feature/D1.4.6.3_profile_overrides_in_target_instance_summary).

**Comment by kurtlenfesty** [comment] 2018-10-04 07:41
@hannakoppelaar I've made the first set of changes -- that the editor appears when the Base Profile is imported. Can you verify that it looks and works the way you want?

**Comment by kurtlenfesty** [comment] 2018-10-04 08:02
I'm a little unclear about the behaviour. If the profile is imported then we show the XML editor (whether or not there's an override on it already). And if we apply the profile, does that changed profile then replace the target's profile string? Or does it only replace the profile override rawProfile?

**Comment by kurtlenfesty** [comment] 2018-10-04 08:42
There's a few problems:
We create a copy of the Target and in the 'Profile' tab we Override Imported Profile: [x].
1. If the HarvesterH3 tries to validate the override XML by creating an 'validateJob' job and for some reason that job isn't cleaned up (the directory 'validateJob' in the H3 harvester live instance), then that directory will persist, and from then on the state will be 'Ready' and not 'Unbuilt', and no validations will succeed. See HarvesterH3.java method build where if (jobStatus.statusDescription.equals("Unbuilt")).
2. The field PO_H3_RAW_PROFILE isn't big enough for the normally exported XML:
Caused by: org.h2.jdbc.JdbcBatchUpdateException: Value too long for column "PO_H3_RAW_PROFILE VARCHAR(255)": "STRINGDECODE('<?xml version=\""1.0\"" encoding=\""UTF-8\""?><!--\r\n  HERITRIX 3 CRAWL JOB CONFIGURATION FILE\r\n\r\n   This is a re... (31295)"; SQL statement:
insert into DB_WCT.PROFILE_OVERRIDES (PO_EXCL_MIME_TYPES, PO_MAX_BYES, PO_MAX_DOCS, PO_MAX_HOPS, PO_MAX_PATH_DEPTH, PO_MAX_TIME_SEC, PO_ROBOTS_POLICY, PO_OR_CREDENTIALS, PO_OR_EXCL_MIME_TYPES, PO_OR_EXCLUSION_URI, PO_OR_INCLUSION_URI, PO_OR_MAX_BYTES, PO_OR_MAX_DOCS, PO_OR_MAX_HOPS, PO_OR_MAX_PATH_DEPTH, PO_OR_MAX_TIME_SEC, PO_OR_ROBOTS_POLICY, PO_H3_DOC_LIMIT, PO_H3_OR_DOC_LIMIT, PO_H3_DATA_LIMIT, PO_H3_OR_DATA_LIMIT, PO_H3_DATA_LIMIT_UNIT, PO_H3_TIME_LIMIT, PO_H3_OR_TIME_LIMIT, PO_H3_TIME_LIMIT_UNIT, PO_H3_MAX_PATH_DEPTH, PO_H3_OR_MAX_PATH_DEPTH, PO_H3_MAX_HOPS, PO_H3_OR_MAX_HOPS, PO_H3_MAX_TRANS_HOPS, PO_H3_OR_MAX_TRANS_HOPS, PO_H3_IGNORE_ROBOTS, PO_H3_OR_IGNORE_ROBOTS, PO_H3_IGNORE_COOKIES, PO_H3_OR_IGNORE_COOKIES, PO_H3_OR_BLOCK_URL, PO_H3_OR_INCL_URL, PO_H3_RAW_PROFILE, PO_H3_OR_RAW_PROFILE, PO_OID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [22001-172]
- For example, the default exported XML for a profile is 30,364 characters. So is there an override limit? Or do we just use a CLOB, the same as P_PROFILE_STRING in the PROFILE table?

**Comment by hannakoppelaar** [comment] 2018-10-04 14:11
You're right, 1) could actually occur, although I haven't seen it happen yet. Do you think it's worth the trouble to automatically detect and fix that problem when it occurs? (Not a rhetorical question ;-))

2) In wct-core/db/latest/upgrade/wct-upgrade-1_6_3-1_7-oracle.sql on the D1.4.6.2 branch the PO_H3_OR_RAW_PROFILE field is of type clob. (And text in mysql and postgresql.) Perhaps you've added that field manually, using a different dataype?

**Comment by hannakoppelaar** [comment] 2018-10-04 14:38
> I'm a little unclear about the behaviour. If the profile is imported then we show the XML editor (whether or not there's an override on it already). And if we apply the profile, does that changed profile then replace the target's profile string? Or does it only replace the profile override rawProfile?

I feel the ti summary page is a bit ambiguous anyway, but I guess updating just the PO_H3_RAW_PROFILE makes more sense to me, since it's supposed to be an override of the base profile (the title of that section of the screen is "Profile Overrides" after all).

**Comment by kurtlenfesty** [comment] 2018-10-04 17:35
For 1) I'll have it automatically detect and fix the problem.
For 2) that's the field type in the H2 database, so I'll look into why it didn't use the CLOB type, since that's the type that shows up for P_Profile_String.

I'll also have the 'apply profile' button make the change the PO_H3_Raw_Profile.

I see that you've pushed another commit to D1.4.6.2, so I'll pull that into my branch as well.

**Comment by kurtlenfesty** [comment] 2018-10-09 01:12
Pull request [pull/55](https://github.com/DIA-NZ/webcurator/pull/55). Note that D1.4.6.2 should be merged into master first, as those features are included. See the pull request itself for identified issues.

**Comment by obrienben** [comment] 2018-10-25 09:00
Closed by #56

**Closed by obrienben** 2018-10-25 09:00 UTC
